### ISSUE TITLE
Implement conditional __repr__()

### ISSUE THREAD

**Issue by capsulecorplab** [spacedecentral/SysML.py#33]
Need a way for `__repr__()` in `ModelElement`, to return a short or long formatted string element depending on whether it was called from within a dict(), or directly on the object itself. e.g., 

```
>>> bar1
name: bar name 1
stereotype: «block» 
parts: []
references: []
values: []
constraints: []
flows: []
multiplicity: []
uuid: a14fdf5e-b4d7-11e8-8170-089e0132c719
>>> foo
name: foo name
stereotype: «block» 
parts:
    'bar1' : «block» bar name 1
    'bar2' : «block» bar name 2
references: []
values: []
constraints: []
flows: []
multiplicity: []
uuid: c7aec630-b4b7-11e8-8170-089e0132c719
```

A `__repr__()` decorator seems to make the most sense.

**Comment by cisko3000** [comment]
What about for __repr__()
`<Block[name_here]:parts(x)>`
where x is a count of parts. And for __str__, something like in first post:
`name: foo
stereotype: «block» 
parts: {
    'bar1' : «block» long bar name 1
    'bar2' : «block» long bar name 2
}`
Reason for my suggestion is that when debugging, if a repr of Block shows up in a log, it won't make the log slower to read. Sometimes, overly descriptive repr's will throw off the identation on print outs or logs and it makes debugging less pleasant. If someone wants a full representation of the Block, they can do str() explicitly. What do you think about this approach?

BTW, I don't know anything about this project, but it's an interesting issue.

**Comment by capsulecorplab** [comment]
Thanks for the suggestion, @cisko3000! I do like the ability to debug... Though, without getting into too much detail, I think for the purposes of this project it, may have to break from certain python repr() conventions a bit. If there's a way to write conditionals in __repr__() wherein it would have custom return elements depending on whether it was called from within a dict(), or if it was a direct call of the object itself, that would be ideal. i.e., something like
```
>>> bar1
name: long bar name 1
stereotype: «block» 
parts: []
>>> foo
name: long foo name
stereotype: «block» 
parts: {
    'bar1' : «block» long bar name 1
    'bar2' : «block» long bar name 2
}
```

**Comment by cisko3000** [comment]
That's a cool idea, I've never thought about something like that. I looked
it up, there is the inspect module, maybe you can decorate the repr method
with a function that uses inspect.

I still have to see what this project actually does, I didn't really
understand it. Interesting implementation concept though.

**Comment by capsulecorplab** [comment]
Hm. Haven't heard of the inspect module, but a __repr__() decorator sounds like a good idea. @cisko3000 would you be interested in working on this? If so, I can create a branch with updated unit tests for an easy PR

**Comment by cisko3000** [comment]
I'd be up for it but I don't know anything about model based system engineering. Are you using this project in real life? for a start up or design of something?

**Comment by capsulecorplab** [comment]
Okay. I created a new branch, [33-implement-conditional-repr](https://github.com/spacedecentral/SysML.py/tree/33-implement-conditional-repr), with notes in the [commit](https://github.com/spacedecentral/SysML.py/commit/034bbc56a3018a7f4802ca6a49533b0f455d0c41), for getting started on this issue. Let me know if anything seems unclear.

Domain knowledge or expertise of model-based systems engineering isn't really needed for the scope of this particular issue, but if you're interested, the [readme](https://github.com/spacedecentral/SysML.py/blob/dev/README.md) has some good links on the subject. No hard plans to use this project _IRL_ as of yet, as it's still very much under development. Though, it would be nice to at least release a beta on PyPI :slightly_smiling_face:

**Comment by capsulecorplab** [comment]
Just opened a [similar issue](https://github.com/capsulecorplab/mindgraph/issues/4) on another project. Might provide some insights for how to tackle this one :slightly_smiling_face:

**Comment by capsulecorplab** [comment]
Decided to replace this with "pythonic" repr. May implement a `__str__() ` method that prints the above behavior later
